apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: troyhart
    provider: github
    repository: spring-demo4jx1
  name: troyhart-spring-demo4jx1
spec:
  description: Imported application for troyhart/spring-demo4jx1
  httpCloneURL: https://github.com/troyhart/spring-demo4jx1.git
  org: troyhart
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: spring-demo4jx1
  scheduler:
    kind: ""
    name: ""
  url: git@github.com:troyhart/spring-demo4jx1.git
