adminUser:
  password: local:mosops/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: thart@myriad.com
  token: local:mosops/pipelineUser:token
  username: troyhart
prow:
  hmacToken: local:mosops/prow:hmacToken
